#!/bin/bash

set -e

export FFMPEG_PATH=$(which ffmpeg)

cd /var/www/html

if [ ! -f .env ]
then
  echo ".env not present. bootstrapping..."
  echo "generating app key"
  echo "APP_KEY=$(php artisan key:generate --show)" >> .env
else
  echo "environment file exists, skipping bootstrap"
fi

echo "running docker-php-entrypoint with arguments $@"

docker-php-entrypoint $@
